### ISSUE TITLE
Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf

### ISSUE THREAD

**Issue by htilly** [cmulk/wireguard-docker#15]
Everything works except for DNS queries. Problem seems to be as the title says:
/etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf

If I manually configure /etc/resolv.conf to 1.1.1.1 or similar everything works as expected. 
/etc/resolvconf/run/resolv.conf contains the correct info.

dpkg-reconfigure resolvconf seems to be a way forward...

Logs:
```
Attaching to wireguard
wireguard           | Wed Apr  8 07:56:59 UTC 2020: Starting Wireguard /etc/wireguard/wg0.conf
wireguard           | [#] ip link add wg0 type wireguard
wireguard           | [#] wg setconf wg0 /dev/fd/63
wireguard           | [#] ip -4 address add 172.xx.xxx.xx/32 dev wg0
wireguard           | [#] ip -6 address add xxxx:0000:xxxx:cafe:1111:1111:xxf9:xxxx/128 dev wg0
wireguard           | [#] ip link set mtu 1420 up dev wg0
wireguard           | [#] resolvconf -a tun.wg0 -m 0 -x
wireguard           | /etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /etc/resolvconf/run/resolv.conf
wireguard           | [#] wg set wg0 fwmark 51820
wireguard           | [#] ip -6 route add ::/0 dev wg0 table 51820
wireguard           | [#] ip -6 rule add not fwmark 51820 table 51820
wireguard           | [#] ip -6 rule add table main suppress_prefixlength 0
wireguard           | [#] ip6tables-restore -n
wireguard           | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
wireguard           | [#] ip -4 rule add not fwmark 51820 table 51820
wireguard           | [#] ip -4 rule add table main suppress_prefixlength 0
wireguard           | [#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
wireguard           | [#] iptables-restore -n
wireguard           | Adding iptables NAT rule

```

My docker-compose:

```
wireguard:
  container_name: wireguard
  image: cmulk/wireguard-docker:buster
  volumes:
    - /config/wireguard:/etc/wireguard
    - /lib/modules:/lib/modules
  ports:
    - 9929:9929/udp
  restart: unless-stopped
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  sysctls:
  ### Unable to get it working without these settings. Running IPv6 on the host.
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
  privileged: true
```
